### ISSUE TITLE
compile 'com.firebase.firebase-ui:0.2.0' is not working

### ISSUE THREAD

**Issue by ghost** [firebase/FirebaseUI#1]
README.md states
compile 'com.firebase.firebase-ui:0.2.0' to be used for gradle. However this is not working for me. So I used
compile 'com.firebaseui:firebase-ui:0.2.0' after checking Maven Central.

I'm new to gradle builds. I would like to confirm the correct dependency.

**Comment by puf** [comment]
Hi asifahmed11, the correct dependency for 0.2 is `compile 'com.firebaseui:firebase-ui:0.2.0'`. You can prevent this type of problem by using the visual dependency dialog (as shown in the README) in Android Studio and searching for `firebase-ui`. That will ensure you get the right groupId and version automatically.

**Comment by puf** [comment]
Aha... I now noticed the typo. Sorry about that. Fixed.

**Comment by ghost** [comment]
Okay. Thanks a lot for clearing my doubt. :)
