### ISSUE TITLE
pagination/infinite scroll

### ISSUE THREAD

**Issue by ghost** [firebase/FirebaseUI#3]
I'm new in firebase.
Is Infinite scroll (or pagination) realized?
If not, how can i implement infinite scroll in my android app?
Please save my day!!!

Sorry for my english

**Comment by samtstern** [comment]
@proudUzbek please see the documentation for [Firebase Query](https://firebase.google.com/docs/reference/android/com/google/firebase/database/Query), specifically the `startAt` and `endAt` functions if you'd like to implement pagination.  

This is not something that would be a feature of FirebaseUI.
