### ISSUE TITLE
Firebase Recycler Adapter : Endless scrolling

### ISSUE THREAD

**Issue by michaelspeed** [firebase/FirebaseUI#5]
any way we can implement this now, if anyone has figured it out?

**Comment by samtstern** [comment]
@michaelspeed I assume what you want is pagination?  Endless scrolling is the default behavior of FirebaseUI.

I'd suggest viewing the discussion on either the Android or iOS repositories as this repo is not actively used for feature request discussions.  See here:
Android - https://github.com/firebase/FirebaseUI-iOS/issues/9
iOS - https://github.com/firebase/FirebaseUI-Android/issues/110
